### PR TITLE
ipv6 ovs NM lifetime handling fix

### PR DESCRIPTION
**Pull request by AlbertHaw**
The callback_IPv6_Address() in NM were invoked due to ovs IPv6_Address entry got modified, it assume new IPv6 address or prefix were changed as a result of new DHCP handshake.  It come with a full sequence of flushing all existing address provision on interfaces & kick off DAD detection , etc. 						
						
However if the only changes are lifetime (valid & preferred) (eg. during  DHCP_RENEW), the existing logic is treating it as a new IPv6 address are provisioned (callback triggered can only tell ovsdb IPv6_Address entry got modified but did not distinguish whether the only changes are lifetime) & kick off the full sequence of IPv6 address provision as described above. Which causes LAN side disruption whenever DHCP_RENEW is happening.						
						
The proposed logic just distinguish whether the only changes were lifetime while everything else are same, if so then skip the further action of nm2_ipv6_address_update() that follows.						
						
Note: The schema has following definition (per schema_pre.h):
struct schema_IPv6_Address	
{	
 int _update_type;	
 ovs_uuid_t _uuid;	
 ovs_uuid_t _version;	
 char address_status[128 + 1];	
 char prefix[49 + 1];	
 char address[49 + 1];	
 char valid_lifetime[64 + 1];	
 char preferred_lifetime[64 + 1];	
 char origin[128 + 1];	
 char status[128 + 1];	
 _Bool enable;	
 };

### CODE REVIEW

**Comment by AlbertHaw** [comment]
The issue were reported by a tier-1 service provider in US as a P1(severe) issue, as the LAN side disruption is very prominent. Basically it defeat the purpose of DHCP_RENEW.

**Comment by mitja-plume** [comment]
Hi @AlbertHaw,

can you describe how prominent the issue is?

Do I understand this correctly that the issue happens when a new DHCPv6 renew is issued to the client with updated IANA/IAPD settings (no matter which ones), the LAN side is re-provisioned, this means that the IPv6 address is re-applied to the LAN interface which might be causing the disruption.

However, since your patch seems to help, it seems that the issue is just the reassignment of the IP to the LAN interface? Is that correct?

**Comment by mitja-plume** [comment]
Your changes effectively make NM ignore any updates to the IPv6 address lifetimes. I'm not sure if I'm completely OK with the changes as it may break other things.

**Comment by AlbertHaw** [comment]
Hi, @mitja-plume 								
1. The disruption could go as much as 6-8 seconds, which is very noticeable.								
2. Although the changes make NM ignore the updating of the lifetime (only under the condition when the only changes are lifetime), the lifetime values are still been recorded & populated to the related table (i.e. DHCP_Option table & IPv6_Prefix table.) correctly.								
3. I'll add comment & re-send the PR, noting the consequences.								
4. Agree that if a better or complementary solution is available, we should revisit the issue.

**Comment by AlbertHaw** [comment]
Hi,  @mitja-plume

I have checked in the code with more comment as previously discussed.
Do I need to close the current PR & re-create a brand new one ? Not sure how I should proceed.

**Comment by AlbertHaw** [comment]
Hi, @mitja-plume,

I have added more comment as previously discussed.

**Pull request closed without merging**
